### ISSUE TITLE
Filters list empty

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/ReportsWebApp#119] opened 2017-12-20 02:15 UTC
https://github.com/AdguardTeam/AdguardFilters/issues/8621

According to issue above the reporting tool allows to continue if no filter is selected.

**Comment by vbagirov** [comment] 2017-12-20 14:06
Honestly, I can't reproduce it. Are there more examples of such behavior?

**Comment by BlazDT** [comment] 2017-12-20 14:17
That is the first one I have seen so far.

**Comment by vbagirov** [comment] 2017-12-20 14:37
@BlazDT please post here if you come across more.

**Comment by vbagirov** [comment] 2018-06-22 14:02
Still cant reproduce, please reopen if you can reproduce the issue consistently. Closing for now.

**Closed by vbagirov** 2018-06-22 14:02 UTC
Labels: P4: Low
