### ISSUE TITLE
Cannot render screenshots for some cases

### ISSUE THREAD

**Issue by vitalkanev** [AdguardTeam/ReportsWebApp#98] opened 2017-11-26 17:21 UTC
AdguardTeam/AdguardFilters/issues/7923 (**this is not a test ticket**) in screenshot 1.
Not rendered properly, but the link inside works.

**Comment by ameshkov** [comment] 2017-11-26 20:14
@seanl-adg slightly wrong format, you need a new line there

**Comment by seanl-adg** [comment] 2017-11-26 20:19
I'm afraid that this is caused by @sc's modification of url regex. 
This can only happen if the input screenshot url was a concatenation of 2 urls which is space-separated, like `https://s17.postimg.org/hbqbx6hb3/image.png https://s17.postimg.org/71nwxyekv/image.png`, and the modified url regex validates it even though it is an invalid url. When it is used as `src` attribute of an `img` tag, it seems that the browser uses the part before the first whitespace.

**Comment by ameshkov** [comment] 2017-11-26 20:27
Funny thing is that `https://s17.postimg.org/hbqbx6hb3/image.png https://s17.postimg.org/71nwxyekv/image.png` is basically a valid URL anyway.

Ok, got it, not a bug then.

**Comment by seanl-adg** [comment] 2017-11-26 21:22
I'm not sure in what sense you are talking a "valid URL". According to the URL specification, `'\u0020'` cannot appear in the url path, so it is absolutely an invalid url. What's funny is that browser's html parser is so permissive that it anyway displays the image.

**Comment by ameshkov** [comment] 2017-11-26 21:50
@seanl-adg I'm just thinking that'd be too much to ask people to supply an encoded URL every time. Browsers, for instance, don't require doing it in the address bar so why should we?

**Comment by seanl-adg** [comment] 2017-11-26 21:51
Github Markdown parser cannot parse it.

**Comment by ameshkov** [comment] 2017-11-26 21:52
I realize it, but I don't think it's important enough to harden validation for such a minor issue

**Comment by sc0rp10** [comment] 2017-11-27 11:07
@seanl-adg you shouldn't validate screenshot URI with regex, you should use `Image.onload()`

**Comment by ameshkov** [comment] 2017-11-27 16:07
No need to argue over a minor wontfix issue

**Closed by ameshkov** 2017-11-27 16:07 UTC
Labels: wontfix

**Comment by ministr91** [comment] 2017-11-30 23:06
@vitalkanev не понимаю, ты же по-русски писать можешь, зачем создавать тему по-английски? Разработчик тоже русский

**Comment by ameshkov** [comment] 2017-11-30 23:07
@ministr91 ну вообще Шон по-русски не говорит.

**Comment by vitalkanev** [comment] 2017-12-01 07:33
Я говорю по-русски. Но если тикет в описании на английском

**Comment by ministr91** [comment] 2017-12-01 10:01
@ameshkov как не говорит? Ниже неплохо пишет
@vitalkanev ну ладно

**Comment by ameshkov** [comment] 2017-12-01 10:06
При чем тут он:( Ладно, все, закрыли тему
